//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionsWeb2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auction()
        {
            this.Bids = new HashSet<Bid>();
        }
    
        public int Id { get; set; }
        public string IdUser { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<decimal> PriceStart { get; set; }
        public Nullable<decimal> PriceNow { get; set; }
        public Nullable<decimal> PriceEnd { get; set; }
        public Nullable<System.DateTime> TimeCreate { get; set; }
        public Nullable<System.DateTime> TimeOpen { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public string State { get; set; }
        public string Winner { get; set; }
        public Nullable<int> TotalTokens { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
    }
}
